config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'campaigns#index'
  resources :campaigns, controller: 'campaigns', model: 'Campaign'
  resources :contacts, controller: 'contacts', model: 'Contact'
  resources :transactions, controller: 'transactions', model: 'Transaction'
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/campaign.rb
# frozen_string_literal: true

class Campaign < ApplicationRecord
  validates :name, :budget, :description, presence: true

  has_and_belongs_to_many :contacts, uniq: true
  has_and_belongs_to_many :campaign_transactions, class_name: 'Transaction', uniq: true

  accepts_nested_attributes_for :campaign_transactions, reject_if: :all_blank, allow_destroy: true
  accepts_nested_attributes_for :contacts, reject_if: :all_blank, allow_destroy: true

  # Filter Reocrds
  def self.filter_records(args)
    if args[:_type] == 'query'
      Campaign.where('lower(name) LIKE ?', "%#{args[:term].downcase}%")
    else
      Campaign.includes(:contacts, :campaign_transactions)
              .order(created_at: :desc).paginate(page: args[:page], per_page: 10)
    end
  end
end

app/models/contact.rb
# frozen_string_literal: true

class Contact < ApplicationRecord
  validates :first_name, :mobile, presence: true
  validates :email, presence: true, format: { with: URI::MailTo::EMAIL_REGEXP }, uniqueness: true
  validates :mobile, format: { with: /\A\d{10}\z/, message: 'should be a 10-digit number' }

  has_and_belongs_to_many :campaigns, uniq: true
  has_and_belongs_to_many :contact_transactions, class_name: 'Transaction', uniq: true

  accepts_nested_attributes_for :campaigns, reject_if: :all_blank, allow_destroy: true
  accepts_nested_attributes_for :contact_transactions, reject_if: :all_blank, allow_destroy: true

  # Filter Reocrds
  def self.filter_records(args)
    if args[:_type] == 'query'
      Contact.where('lower(email) LIKE ?', "%#{args[:term].downcase}%")
    else
      Contact.includes(:campaigns, :contact_transactions)
             .order(created_at: :desc).paginate(page: args[:page], per_page: 10)
    end
  end
end

app/models/transaction.rb
# frozen_string_literal: true

class Transaction < ApplicationRecord
  validates :price, :description, presence: true

  has_and_belongs_to_many :campaigns, uniq: true
  has_and_belongs_to_many :contacts, uniq: true

  accepts_nested_attributes_for :campaigns, reject_if: :all_blank, allow_destroy: true
  accepts_nested_attributes_for :contacts, reject_if: :all_blank, allow_destroy: true

  # Filter Reocrds
  def self.filter_records(args)
    if args[:_type] == 'query'
      Transaction.where('lower(description) LIKE ?', "%#{args[:term].downcase}%")
    else
      Transaction.includes(:contacts, :campaigns).order(created_at: :desc)
                 .paginate(page: args[:page], per_page: 10)
    end
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/campaigns_controller.rb
# frozen_string_literal: true

class CampaignsController < ApplicationController
  before_action :fetch_campaign, except: [:create]

  def index
    @campaign ||= Campaign.new
    @campaigns = Campaign.filter_records(params)
    respond_to do |format|
      format.html
      format.js { render json: @campaigns }
    end
  end

  def create
    @campaign = Campaign.new(campaign_params)
    @campaign.save
  end

  def update
    @campaign.update_attributes(campaign_params)
  end

  def destroy
    @success = if @campaign&.destroy
                 true
               else
                 false
               end
  end

  private

  def fetch_campaign
    @campaign = Campaign.find_by(id: params[:id])
  end

  def campaign_params
    params.require(:campaign).permit(:id, :name, :budget, :description,
                                     contact_ids: [], campaign_transaction_ids: [],
                                     contacts_attributes: %i[id first_name last_name email mobile _destroy],
                                     campaign_transactions_attributes: %i[id price description _destroy])
  end
end

app/controllers/contacts_controller.rb
# frozen_string_literal: true

class ContactsController < ApplicationController
  before_action :fetch_contact, except: [:create]

  def index
    @contact ||= Contact.new
    @contacts = Contact.filter_records(params)

    respond_to do |format|
      format.html
      format.js { render json: @contacts }
    end
  end

  def create
    @contact = Contact.new(contact_params)
    @contact.save
  end

  def update
    @contact.update(contact_params)
  end

  def destroy
    @success = if @contact.destroy
                 true
               else
                 false
               end
  end

  private

  def fetch_contact
    @contact = Contact.find_by(id: params[:id])
  end

  def contact_params
    params.require(:contact).permit(:id, :first_name, :last_name, :email, :mobile,
                                    campaign_ids: [], contact_transaction_ids: [],
                                    campaigns_attributes: %i[id name budget description _destroy],
                                    contact_transactions_attributes: %i[id price description _destroy])
  end
end

app/controllers/transactions_controller.rb
# frozen_string_literal: true

class TransactionsController < ApplicationController
  before_action :fetch_transaction

  def index
    @transaction ||= Transaction.new
    @transactions = Transaction.filter_records(params)
    respond_to do |format|
      format.html
      format.js { render json: @transactions }
    end
  end

  def create
    @transaction = Transaction.new(transaction_params)
    @transaction.save
  end

  def update
    @transaction.update_attributes(transaction_params)
  end

  def destroy
    @success = if @transaction.destroy
                 true
               else
                 false
               end
  end

  private

  def fetch_transaction
    @transaction = Transaction.find_by(id: params[:id])
  end

  def transaction_params
    params.require(:transaction).permit(:id, :price, :description,
                                        campaign_ids: [], contact_ids: [],
                                        campaigns_attributes: %i[id name budget description _destroy],
                                        contacts_attributes: %i[id first_name last_name email mobile _destroy])
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
  def navbar_active(nav)
    'active' if nav == params[:controller]
  end
end

app/helpers/form_helper.rb
# frozen_string_literal: true

module FormHelper
  def errors_for(form, field)
    content_tag(:p, form.object.errors[field].try(:first), class: 'help-block')
  end

  def form_group_for(form, field, opts = {}, &block)
    label = opts.fetch(:label, true)
    has_errors = form.object.errors[field].present?
    content_tag :div, class: "form-group #{'has-error' if has_errors}" do
      concat form.label(field, class: 'control-label') if label
      concat capture(&block)
      concat errors_for(form, field)
    end
  end
end

app/views/campaigns/_campaign.html.erb
<tr id="campaign-data-<%= campaign.id %>">
  <%= render "record", campaign: campaign %>
</tr>

app/views/campaigns/_form.html.erb
<div class="form-container">

	<%= semantic_form_for campaign, html: { autocomplete: 'off', class: 'form-horizontal'}, remote: true do |f| %>

	 	<%= f.input :name, label: true, input_html: { class: 'form-control' } %>
	 	<%= f.input :budget, label: true, input_html: { class: 'form-control' } %>
	 	<%= f.input :description, label: true, input_html: { class: 'form-control', rows: '2' } %>

	 	<%= f.inputs 'Contacts' do %>
	 		<%= f.input :contact_ids, label: "Select Contacts", collection: campaign.contacts.pluck(:email, :id), as: :select, input_html: { class: "custom-select-contact",  data: { url: campaigns_url } }, multiple: true %>

	 		<%= f.inputs 'Or Create Contacts' do %>
	 			<%= f.semantic_fields_for :contacts, campaign.contacts.presence || campaign.contacts.new do |contact| %>
	 				<%= render 'shared/contact_fields', f: contact %>
	 			<% end %>
	 			<div class="add_more_field">
        	<%= link_to_add_association('+ Add More', f, :contacts, class: 'btn primary', partial: 'shared/contact_fields') %>
	 			</div>
	 		<% end %>
	 	<% end %>

	 	<%= f.inputs 'Transactions' do %>
	 		<%= f.input :campaign_transaction_ids, label: "Select Transactions", collection: campaign.campaign_transactions.pluck(:description, :id), as: :select, input_html: { class: "custom-select-transaction" }, multiple: true %>

	 		<%= f.inputs 'Or Create New Transaction' do %>
	 			<%= f.semantic_fields_for :campaign_transactions, campaign.campaign_transactions.presence || campaign.campaign_transactions.new do |transaction| %>
	 				<%= render 'shared/transaction_fields', f: transaction %>
	 			<% end %>
	 			<div class="add_more_field">
        	<%= link_to_add_association('+ Add More', f, :campaign_transactions, class: 'btn primary', partial: 'shared/transaction_fields') %>
	 			</div>
	 		<% end %>
	 	<% end %>

	 	<%= f.submit "#{campaign.persisted? ? 'Update' : 'Create'}", class: 'btn btn-primary' %>
	<% end %>
</div>

app/views/campaigns/_record.html.erb
<th scope="row"><%= campaign.id %></th>
<td><%= campaign.name %></td>
<td><%= campaign.budget %></td>
<td><%= campaign.description %></td>
<td><%= campaign.contacts.pluck(:email).join(", ") %></td>
<td><%= campaign.campaign_transactions.pluck(:price).join(", ") %></td>
<td><%= link_to 'Edit', campaigns_path(id: campaign.id) %></td>
<td><%= link_to 'Delete', campaign_path(id: campaign.id), method: :delete, remote: true %></td>

app/views/campaigns/create.js.erb
<% if @campaign.errors.present? %>
	$('#campaign-form').html("<%= escape_javascript render(partial: 'campaigns/form', locals: { campaign: @campaign }) %>");
<% else %>
	$('#campaign-table').prepend("<%= escape_javascript render(partial: 'campaigns/campaign', locals: { campaign: @campaign }) %>");
<% end %>
contactAutocomplete();
transactionAutocomplete();

app/views/campaigns/destroy.js.erb
<% if @success %>
	$('#campaign-data-<%= @campaign.id %>').html("");
<% end %>

app/views/campaigns/index.html.erb
<div class="container">
	<div id="campaign-form">
		<%= render 'form', campaign: @campaign %>
	</div>
	<div class="data">
		<h2> Records </h2>
		<table class="table" id="campaign-table">
		  <thead>
		    <tr>
		      <th scope="col">#</th>
		      <th scope="col">Name</th>
		      <th scope="col">Budget</th>
		      <th scope="col">description</th>
		      <th scope="col">Contacts</th>
		      <th scope="col">Transactions</th>
		      <th scope="col">Edit</th>
		      <th scope="col">Delete</th>
		    </tr>
		  </thead>
  		<tbody>
  			<%= render partial: 'campaign', collection: @campaigns %>
			</tbody>
		</table>
	</div>
	<%= will_paginate @campaigns %>
</div>

app/views/campaigns/update.js.erb
<% if @campaign.errors.present? %>
	$('#campaign-form').html("<%= escape_javascript render(partial: 'campaigns/form', locals: { campaign: @campaign }) %>");
<% else %>
	$('#campaign-data-<%= @campaign.id %>').html("<%= escape_javascript render(partial: 'campaigns/record', locals: { campaign: @campaign }) %>");
<% end %>
contactAutocomplete();
transactionAutocomplete();

app/views/contacts/_contact.html.erb
<tr id="contact-data-<%= contact.id %>">
  <%= render "record", contact: contact %>
</tr>

app/views/contacts/_form.html.erb
<div class="form-container">

	<%= semantic_form_for contact, html: { autocomplete: 'off', class: 'form-horizontal '}, remote: true do |f| %>

	 	<%= f.input :first_name, label: true, input_html: { class: 'form-control' } %>
	 	<%= f.input :last_name, label: true, input_html: { class: 'form-control' } %>
	 	<%= f.input :email, label: true, input_html: { class: 'form-control' } %>
	 	<%= f.input :mobile, label: true, input_html: { class: 'form-control' } %>

	 	<!-- Starting adding multiple campaigns -->
	 	<%= f.inputs 'Campaigns' do %>
	 		<%= f.input :campaign_ids, label: "Select Campaigns", collection: contact.campaigns, as: :select, input_html: { class: "custom-select-campaign",  data: { url: campaigns_url } }, multiple: true %>
	 		<%= f.inputs 'Or Create New Campaign' do %>
	 			<%= f.semantic_fields_for :campaigns, contact.campaigns.presence || contact.campaigns.new do |campaign| %>
	 				<%= render 'shared/campaign_fields', f: campaign %>
	 			<% end %>
	 			<div class="add_more_field">
        	<%= link_to_add_association('+ Add More', f, :campaigns, class: 'btn primary', partial: 'shared/campaign_fields') %>
	 			</div>
	 		<% end %>
	 	<% end %>
	 	<!-- End adding multiple campaigns -->

	 	<!-- Starting adding multiple transactions -->
	 	<%= f.inputs 'Transactions' do %>
	 		<%= f.input :contact_transaction_ids, label: "Select Transactions", collection: contact.contact_transactions.pluck(:description, :id), as: :select, input_html: { class: "custom-select-transaction" }, multiple: true %>

	 		<%= f.inputs 'Or Create New Transaction' do %>
	 			<%= f.semantic_fields_for :contact_transactions, contact.contact_transactions.presence || contact.contact_transactions.new do |transaction| %>
	 				<%= render 'shared/transaction_fields', f: transaction %>
	 			<% end %>
	 			<div class="add_more_field">
        	<%= link_to_add_association('+ Add More', f, :contact_transactions, class: 'btn primary', partial: 'shared/transaction_fields') %>
	 			</div>
	 		<% end %>
	 	<% end %>
	 	<!-- End adding multiple transactions -->

	 	<%= f.submit "#{contact.persisted? ? 'Update' : 'Create'}", class: 'btn btn-primary' %>
	<% end %>
</div>

app/views/contacts/_record.html.erb
<th scope="row"><%= contact.id %></th>
<td><%= contact.first_name %></td>
<td><%= contact.last_name %></td>
<td><%= contact.email %></td>
<td><%= contact.mobile %></td>
<td><%= contact.campaigns.pluck(:name).join(", ") %></td>
<td><%= contact.contact_transactions.pluck(:price).join(", ") %></td>
<td><%= link_to 'Edit', contacts_path(id: contact.id) %></td>
<td><%= link_to 'Delete', contact_path(id: contact.id), method: :delete, remote: true %></td>

app/views/contacts/create.js.erb
<% if @contact.errors.present? %>
	$('#contact-form').html("<%= escape_javascript render(partial: 'contacts/form', locals: { contact: @contact }) %>");
<% else %>
	$('#contact-table').prepend("<%= escape_javascript render(partial: 'contacts/contact', locals: { contact: @contact }) %>");
<% end %>
campaignAutocomplete();
transactionAutocomplete();

app/views/contacts/destroy.js.erb
<% if @success %>
	$('#contact-data-<%= @contact.id %>').html("");
<% end %>

app/views/contacts/index.html.erb
<div class="container">
	<div id="contact-form">
		<%= render 'form', contact: @contact %>
	</div>
	<div class="data">
		<h2> Records </h2>
		<table class="table" id="contact-table">
		  <thead>
		    <tr>
		      <th scope="col">#</th>
		      <th scope="col">First Name</th>
		      <th scope="col">Last Name</th>
		      <th scope="col">Email</th>
		      <th scope="col">phone</th>
		      <th scope="col">Campaigns</th>
		      <th scope="col">Transactions</th>
		      <th scope="col">Edit</th>
		      <th scope="col">Delete</th>
		    </tr>
		  </thead>
  		<tbody>
				<%= render partial: 'contact', collection: @contacts %>
			</tbody>
		</table>
	</div>
	<%= will_paginate @contacts %>
</div>

app/views/contacts/update.js.erb
<% if @contact.errors.present? %>
	$('#contact-form').html("<%= escape_javascript render(partial: 'contacts/form', locals: { contact: @contact }) %>");
<% else %>
	$('#contact-data-<%= @contact.id %>').html("<%= escape_javascript render(partial: 'contacts/record', locals: { contact: @contact }) %>");
<% end %>
campaignAutocomplete();
transactionAutocomplete();

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CampaignApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= yield %>
  </body>
</html>

app/views/shared/_campaign_fields.html.erb
<div class="nested-fields">
	<%= f.input :name, input_html: { class: 'form-control' } %>
	<%= f.input :budget, input_html: { class: 'form-control' } %>
	<%= f.input :description, input_html: { class: 'form-control', rows: '4' } %>
	<%= link_to_remove_association "Remove Slot", f, class: 'btn primary pull-right' %>
</div>

app/views/shared/_contact_fields.html.erb
<div class="nested-fields">
	<%= f.input :first_name, label: true, input_html: { class: 'form-control' } %>
 	<%= f.input :last_name, label: true, input_html: { class: 'form-control' } %>
 	<%= f.input :email, label: true, input_html: { class: 'form-control' } %>
 	<%= f.input :mobile, label: true, input_html: { class: 'form-control' } %>
 	<%= link_to_remove_association "Remove Slot", f, class: 'btn primary pull-right' %>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to "Campaigns", campaigns_path, class: "nav-link #{navbar_active('campaigns')}" %>
        </li>
        <li class="nav-item">
          <%= link_to "Contacts", contacts_path, class: "nav-link #{navbar_active('contacts')}" %>
        </li>
         <li class="nav-item">
          <%= link_to "Transactions", transactions_path, class: "nav-link #{navbar_active('transactions')}" %>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/shared/_transaction_fields.html.erb
<div class="nested-fields">
	<%= f.input :price, input_html: { class: 'form-control' } %>
	<%= f.input :description, input_html: { class: 'form-control', rows: '4' } %>

	<%= link_to_remove_association "Remove Slot", f, class: 'btn primary pull-right' %>
</div>

app/views/transactions/_form.html.erb
<div class="form-container">

	<%= semantic_form_for transaction, html: { autocomplete: 'off', class: 'form-horizontal '}, remote: true do |f| %>

	 	<%= f.input :price, label: true, input_html: { class: 'form-control' } %>
	 	<%= f.input :description, label: true, input_html: { class: 'form-control', rows: '2' } %>

	 	<!-- Starting adding multiple contacts -->
	 	<%= f.inputs 'Contacts' do %>
	 		<!-- Autocomplete select contacts -->
	 		<%= f.input :contact_ids, label: "Select Contacts", collection: transaction.contacts.pluck(:email, :id), as: :select, input_html: { class: "custom-select-contact",  data: { url: contacts_url } }, multiple: true %>

	 		<%= f.inputs 'Or Create Contacts' do %>
	 			<%= f.semantic_fields_for :contacts, transaction.contacts.presence || transaction.contacts.new do |contact| %>
	 				<%= render 'shared/contact_fields', f: contact %>
	 			<% end %>
	 			<div class="add_more_field">
        	<%= link_to_add_association('+ Add More', f, :contacts, class: 'btn primary', partial: 'shared/contact_fields') %>
	 			</div>
	 		<% end %>
	 	<% end %>
	 	<!-- End adding multiple contacts -->

	 	<!-- Starting adding multiple campaigns -->
	 	<%= f.inputs 'Campaigns' do %>
	 		<!-- Autocomplete select campaigns -->
	 		<%= f.input :campaign_ids, label: "Select Campaigns", collection: transaction.campaigns, as: :select, input_html: { class: "custom-select-campaign",  data: { url: transactions_url } }, multiple: true %>

	 		<%= f.inputs 'Or Create New Campaign' do %>
	 			<%= f.semantic_fields_for :campaigns, transaction.campaigns.presence || transaction.campaigns.new do |campaign| %>
	 				<%= render 'shared/campaign_fields', f: campaign %>
	 			<% end %>
	 			<div class="add_more_field">
        	<%= link_to_add_association('+ Add More', f, :campaigns, class: 'btn primary', partial: 'shared/campaign_fields') %>
	 			</div>
	 		<% end %>
	 	<% end %>
	 	<!-- End adding multiple campaigns -->


	 	<%= f.submit "#{transaction.persisted? ? 'Update' : 'Create'}", class: 'btn btn-primary' %>
	<% end %>
</div>

app/views/transactions/_record.html.erb
<th scope="row"><%= transaction.id %></th>
<td><%= transaction.price %></td>
<td><%= transaction.description %></td>
<td><%= transaction.contacts.pluck(:email).join(", ") %></td>
<td><%= transaction.campaigns.pluck(:name).join(", ") %></td>
<td><%= link_to 'Edit', transactions_path(id: transaction.id) %></td>
<td><%= link_to 'Delete', transaction_path(id: transaction.id), method: :delete, remote: true %></td>

app/views/transactions/_transaction.html.erb
<tr id="transaction-data-<%= transaction.id %>">
  <%= render "record", transaction: transaction %>
</tr>

app/views/transactions/create.js.erb
<% if @transaction.errors.present? %>
	$('#transaction-form').html("<%= escape_javascript render(partial: 'transactions/form', locals: { transaction: @transaction }) %>");
<% else %>
	$('#transaction-table').prepend("<%= escape_javascript render(partial: 'transactions/transaction', locals: { transaction: @transaction }) %>");
<% end %>
campaignAutocomplete();
contactAutocomplete();

app/views/transactions/destroy.js.erb
<% if @success %>
	$('#transaction-data-<%= @transaction.id %>').html("");
<% end %>

app/views/transactions/index.html.erb
<div class="container">
	<div id="transaction-form">
		<%= render 'form', transaction: @transaction %>
	</div>
	<div class="data">
		<h2> Records </h2>
		<table class="table" id="transaction-table">
		  <thead>
		    <tr>
		      <th scope="col">#</th>
		      <th scope="col">Price</th>
		      <th scope="col">Description</th>
		      <th scope="col">Contacts</th>
		      <th scope="col">Campaign</th>
		      <th scope="col">Edit</th>
		      <th scope="col">Delete</th>
		    </tr>
		  </thead>
  		<tbody>
				<%= render partial: 'transaction', collection: @transactions %>
			</tbody>
		</table>
	</div>
	<%= will_paginate @transactions %>
</div>

app/views/transactions/update.js.erb
<% if @transaction.errors.present? %>
	$('#transaction-form').html("<%= escape_javascript render(partial: 'transactions/form', locals: { transaction: @transaction }) %>");
<% else %>
	$('#transaction-data-<%= @transaction.id %>').html("<%= escape_javascript render(partial: 'transactions/record', locals: { transaction: @transaction }) %>");
<% end %>
campaignAutocomplete();
contactAutocomplete();